#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
while IFS= read -r -d '' file; do php -l "$file" >/dev/null; done < <(find "$root/homeopathy-encyclopedia" "$root/tests" -type f -name '*.php' -print0 | sort -z)
node --check "$root/homeopathy-encyclopedia/assets/js/encyclopedia-v2.js"
php "$root/tests/v2-invariants.php"
bash "$root/tests/v2-source-invariants.sh"
php "$root/tests/v23-future-invariants.php"
php "$root/tests/v24-80-round-invariants.php"
php "$root/tests/v241-second-80-invariants.php"
php "$root/tests/v242-third-80-final.php"
php "$root/tests/v243-ten-round-regressions.php"
php "$root/tests/v244-ten-round-regressions.php"
php "$root/tests/test-file06-v245-sixth-ten-round-regressions.php"
php "$root/tests/v246-seventh-ten-round-regressions.php"
php "$root/tests/v247-eighth-ten-round-regressions.php"
php "$root/tests/v248-ninth-ten-round-regressions.php"
php "$root/tests/v249-tenth-ten-round-regressions.php"
php "$root/tests/v2410-eleventh-ten-round-regressions.php"
php "$root/tests/v2411-twelfth-ten-round-regressions.php"
php "$root/tests/v2412-thirteenth-ten-round-regressions.php"
php "$root/tests/v2413-fourteenth-ten-round-regressions.php"
php "$root/tests/v2414-fifteenth-ten-round-regressions.php"
php "$root/tests/v2415-sixteenth-twenty-round-regressions.php"
php "$root/tests/v2415-round20-public-id-regressions.php"
php "$root/tests/v2415-round20-delete-governance-regressions.php"
php "$root/tests/v2416-seventeenth-twenty-round-regressions.php"
php "$root/tests/v2417-eighteenth-twenty-round-regressions.php"
python3 -m py_compile "$root/scripts/build-release.py" "$root/scripts/source-tree-hash.py" "$root/scripts/verify-manifest.py"
a="${TMPDIR:-/tmp}/file06-v2.4.17-a.zip"
b="${TMPDIR:-/tmp}/file06-v2.4.17-b.zip"
python3 "$root/scripts/build-release.py" --source "$root/homeopathy-encyclopedia" --output "$a"
python3 "$root/scripts/build-release.py" --source "$root/homeopathy-encyclopedia" --output "$b"
cmp -s "$a" "$b"
sha256sum "$a"
python3 "$root/scripts/source-tree-hash.py" "$root/homeopathy-encyclopedia"
echo "All File 06 v2.4.17 automated checks, inherited review matrices, seventeenth twenty-round regressions and deterministic package comparison passed."
