#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
plugin="$root/homeopathy-encyclopedia"

test -f "$plugin/homeopathy-encyclopedia.php"
test "$(find "$plugin" -type f -name '*.php' | wc -l | tr -d ' ')" -ge 24
test -f "$plugin/includes/class-he-v23-future.php"
test -f "$plugin/includes/class-he-v24-future-schema.php"
test -f "$plugin/includes/class-he-v24-migration-safety.php"
test -f "$plugin/includes/class-he-v24-future-api.php"
test -f "$plugin/includes/class-he-v24-future-privacy.php"
! grep -R --line-number --include='*.php' --include='*.js' --include='*.css' -E '(AKIA[0-9A-Z]{16}|BEGIN (RSA|OPENSSH|EC) PRIVATE KEY)' "$plugin"
grep -q "Version: 2.4.0" "$plugin/homeopathy-encyclopedia.php"
grep -q "HE_SCHEMA_VERSION', 10" "$plugin/homeopathy-encyclopedia.php"
grep -q "HE_CONTRACT_VERSION', '2.4" "$plugin/homeopathy-encyclopedia.php"
grep -q "future_requirement_count' => 18" "$plugin/homeopathy-encyclopedia.php"
grep -q "class-he-v24-migration-safety.php" "$plugin/homeopathy-encyclopedia.php"
grep -q "sabri/v2/file-06" "$plugin/includes/class-he-v2-api.php"
grep -q "کامیاب کیس" "$plugin/includes/class-he-v2-domain.php"
grep -q "SMC_Contracts::assertions" "$plugin/includes/class-he-v2-auth.php"
grep -q "migration_quarantine" "$plugin/includes/class-he-v22-governance.php"
grep -q "he_integrity_acceptance_required" "$plugin/includes/class-he-v22-integrity.php"
grep -q "content-or-review-changed-before-publication" "$plugin/includes/class-he-v22-schedule.php"
grep -q "spelling-recovery" "$plugin/includes/class-he-v22-search.php"
grep -q "he_type_schema_validation_failed" "$plugin/includes/class-he-v22-type-schemas.php"
grep -q "he_dataset_private_by_default" "$plugin/includes/class-he-v22-research-guard.php"
grep -q "file-16" "$plugin/includes/class-he-v22-consumers.php"
grep -q "status='dead-letter'" "$plugin/includes/class-he-v22-operations.php"
grep -q "F06-FUT-018" "$plugin/includes/class-he-v23-future.php"
grep -q "record_hash" "$plugin/includes/class-he-v24-future-schema.php"
grep -q "consumer acknowledgement" "$plugin/includes/class-he-v24-future-schema.php"
grep -q "researcher-identities" "$plugin/includes/class-he-v24-future-api.php"
grep -q "source_concept_id" "$plugin/includes/class-he-v24-future-api.php"
grep -q "version_number" "$plugin/includes/class-he-v24-future-api.php"
grep -q "claims_without_evidence" "$plugin/includes/class-he-v24-future-api.php"
grep -q "wp_privacy_personal_data_exporters" "$plugin/includes/class-he-v24-future-privacy.php"
grep -q "he_v2_privacy_legal_hold" "$plugin/includes/class-he-v24-future-privacy.php"
grep -q "provider_external" "$plugin/includes/class-he-v24-migration-safety.php"
grep -q "researcher_ids" "$plugin/uninstall.php"
grep -q "he_v24_future_maintenance" "$plugin/uninstall.php"
grep -q -- "--he-primary:var(--sabri-color-primary" "$plugin/assets/css/encyclopedia-v2.css"
! grep -q -- "--sabri-primary:#" "$plugin/assets/css/encyclopedia-v2.css"
! grep -R --line-number -- '--he-orange' "$plugin"
grep -q "default='06-homeopathy-encyclopedia-foundation'" "$root/scripts/build-release.py"
grep -q "migration_quarantine" "$plugin/uninstall.php"
echo "File 06 v2.4 source-tree invariants passed."
