#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
plugin="$root/homeopathy-encyclopedia"

test -f "$plugin/homeopathy-encyclopedia.php"
test "$(find "$plugin" -type f -name '*.php' | wc -l | tr -d ' ')" -ge 22
test -f "$plugin/includes/class-he-v23-future.php"
test -f "$plugin/includes/class-he-v24-audit80-hardening.php"
test -f "$plugin/includes/class-he-v24-final-guard.php"
! grep -R --line-number --include='*.php' --include='*.js' --include='*.css' -E '(AKIA[0-9A-Z]{16}|BEGIN (RSA|OPENSSH|EC) PRIVATE KEY)' "$plugin"
grep -q "Version: 2.4.0" "$plugin/homeopathy-encyclopedia.php"
grep -q "HE_SCHEMA_VERSION', 10" "$plugin/homeopathy-encyclopedia.php"
grep -q "HE_CONTRACT_VERSION', '2.4" "$plugin/homeopathy-encyclopedia.php"
grep -q "future_requirement_count' => 18" "$plugin/homeopathy-encyclopedia.php"
grep -q "audit_review_rounds' => 80" "$plugin/homeopathy-encyclopedia.php"
grep -q "sabri/v2/file-06" "$plugin/includes/class-he-v2-api.php"
grep -q "کامیاب کیس" "$plugin/includes/class-he-v2-domain.php"
grep -q "SMC_Contracts::assertions" "$plugin/includes/class-he-v2-auth.php"
grep -q "migration_quarantine" "$plugin/includes/class-he-v22-governance.php"
grep -q "he_integrity_acceptance_required" "$plugin/includes/class-he-v22-integrity.php"
grep -q "content-or-review-changed-before-publication" "$plugin/includes/class-he-v22-schedule.php"
grep -q "spelling-recovery" "$plugin/includes/class-he-v22-search.php"
grep -q "he_type_schema_validation_failed" "$plugin/includes/class-he-v22-type-schemas.php"
grep -q "he_dataset_private_by_default" "$plugin/includes/class-he-v22-research-guard.php"
grep -q "file-16" "$plugin/includes/class-he-v22-consumers.php"
grep -q "status='dead-letter'" "$plugin/includes/class-he-v22-operations.php"
grep -q "F06-FUT-018" "$plugin/includes/class-he-v23-future.php"
grep -q "crossref" "$plugin/includes/class-he-v23-future.php"
grep -q "pubmed" "$plugin/includes/class-he-v23-future.php"
grep -q "clinicaltrials" "$plugin/includes/class-he-v23-future.php"
grep -q "orcid" "$plugin/includes/class-he-v23-future.php"
grep -q "datacite" "$plugin/includes/class-he-v23-future.php"
grep -q "mesh" "$plugin/includes/class-he-v23-future.php"
grep -q "translation-outdated" "$plugin/includes/class-he-v23-future.php"
grep -q "delivery_owner'=>'file-19'" "$plugin/includes/class-he-v23-future.php"
grep -q "visual_owner'=>'file-25'" "$plugin/includes/class-he-v23-future.php"
grep -q "source_concept_id" "$plugin/includes/class-he-v24-audit80-hardening.php"
grep -q "version_number,status,title,summary,content_hash" "$plugin/includes/class-he-v24-audit80-hardening.php"
grep -q "object_type='concept' AND object_id=%d" "$plugin/includes/class-he-v24-audit80-hardening.php"
grep -q "he_future_evidence_source_required" "$plugin/includes/class-he-v24-audit80-hardening.php"
grep -q "limit_response_size" "$plugin/includes/class-he-v24-audit80-hardening.php"
grep -q "translation_source_changed" "$plugin/includes/class-he-v24-audit80-hardening.php"
grep -q "fully_public_concept" "$plugin/includes/class-he-v24-final-guard.php"
grep -q "Idempotency-Key" "$plugin/includes/class-he-v24-final-guard.php"
grep -q "unreviewed_claims" "$plugin/includes/class-he-v24-final-guard.php"
grep -q "dead_letter_impacts" "$plugin/includes/class-he-v24-final-guard.php"
grep -q -- "--he-primary:var(--sabri-color-primary" "$plugin/assets/css/encyclopedia-v2.css"
! grep -q -- "--sabri-primary:#" "$plugin/assets/css/encyclopedia-v2.css"
! grep -R --line-number -- '--he-orange' "$plugin"
grep -q "default='06-homeopathy-encyclopedia-foundation'" "$root/scripts/build-release.py"
grep -q "migration_quarantine" "$plugin/uninstall.php"
echo "File 06 v2.4 source-tree invariants passed."
