<?php
/** File 06 v2.4.15 sixteenth fresh twenty-round regression controls. */
$root=dirname(__DIR__);$fail=array();$upto=(int)(getenv('V2415_ROUND')?:20);
function v2415_read($p){$v=file_get_contents($p);if(false===$v)throw new RuntimeException($p);return $v;}
function v2415_ok($round,$ok,$m){global $fail,$upto;if($round<=$upto&&!$ok)$fail[]="R{$round} {$m}";}
$p=$root.'/homeopathy-encyclopedia';
$domain=v2415_read($p.'/includes/class-he-v2-domain.php');
$api=v2415_read($p.'/includes/class-he-v2-api.php');
$dto=v2415_read($p.'/includes/class-he-v241-public-dto-guard.php');
$schema=v2415_read($p.'/includes/class-he-v2-schema.php');
$browse=v2415_read($p.'/includes/class-he-v242-research-browse.php');
$public=v2415_read($p.'/includes/class-he-v2-public.php');
$bootstrap=v2415_read($p.'/homeopathy-encyclopedia.php');
$readme=v2415_read($p.'/readme.txt');
$runall=v2415_read($root.'/tests/run-all.sh');
$repair_pos=strpos($schema,'public static function repair( $dry_run = true )');$repair=false===$repair_pos?'':substr($schema,$repair_pos);

v2415_ok(1,false!==strpos($dto,"preg_match( '/^[0-9a-f]{8}-[0-9a-f]{4}")&&false!==strpos($dto,"\$edge['source'] = \$resolved['source']")&&false!==strpos($dto,'ctype_digit( $value )'),'canonical UUID graph edges are still destroyed by numeric-only DTO remapping');
v2415_ok(2,false!==strpos($domain,"add_filter( 'pre_delete_post'")&&false!==strpos($domain,"add_action( 'deleted_post'")&&false!==strpos($domain,'verify_pending_deletions')&&false!==strpos($domain,'wordpress-hard-delete-confirmed')&&false===strpos($domain,"add_action( 'before_delete_post'"),'hard-delete lifecycle remains non-vetoable or emits before confirmed deletion');
v2415_ok(3,false!==strpos($api,"/datasets/(?P<id>[0-9a-fA-F]{8}")&&false!==strpos($domain,'Dataset access requests require the canonical public dataset identifier')&&false===strpos($domain,'if ( is_numeric( $research_identifier )'),'dataset request API still accepts raw internal numeric research identifiers');
v2415_ok(4,false!==strpos($api,"/research/(?P<id>[0-9a-fA-F]{8}")&&false!==strpos($api,"WHERE public_id=%s', \$public_id")&&false!==strpos($api,"CAP_RESEARCH, (int) \$row['post_id'], 'file06-rest'"),'research transition still exposes an internal numeric route or lacks object-scoped public-ID resolution');
v2415_ok(5,false!==strpos($api,"/integrity/(?P<id>[0-9a-fA-F]{8}")&&false!==strpos($api,"integrity_actions' ) . ' WHERE public_id=%s"),'integrity apply still exposes internal numeric action IDs');
v2415_ok(6,false!==strpos($api,'ctype_digit( $replacement_identifier )')&&false!==strpos($api,'Replacement entries must use a canonical public identifier or canonical slug')&&false!==strpos($api,"\$replacement_id = (int) \$replacement['id']"),'integrity replacement still accepts raw numeric public identifiers');
v2415_ok(7,false!==strpos($domain,'public static function encode_public_cursor')&&false!==strpos($domain,'public static function decode_public_cursor')&&false!==strpos($domain,"hash_hmac( 'sha256'")&&false!==strpos($domain,"encode_public_cursor( 'entries'")&&false!==strpos($browse,"encode_public_cursor( 'research'")&&false!==strpos($api,"'cursor' => array( 'sanitize_callback' => 'sanitize_text_field'"),'public pagination still leaks/accepts raw database cursors');
v2415_ok(8,false!==strpos($domain,"p.ID=c.post_id AND p.post_type=%s AND p.post_status='publish'")&&false!==strpos($domain,'self::ENTRY_TYPE, $q'),'autocomplete can still reveal a stale/unpublished WordPress projection');
v2415_ok(9,false!==strpos($domain,'research_first_save_projection_failed')&&false!==strpos($domain,"SELECT id,post_id,record_type FROM {\$table} WHERE post_id=%d")&&false!==strpos($domain,'OPTION_SAFE_MODE'),'direct WordPress research saves can still silently miss their canonical projection');
v2415_ok(10,false!==strpos($domain,'entry_projection_update_failed')&&false!==strpos($domain,'entry_save_projection_failed')&&false!==strpos($domain,'return $id ? self::reindex_concept( $id ) : false')&&false!==strpos($domain,'return false !== $deleted'),'entry projection/reindex persistence can still silently fail');
v2415_ok(11,false!==strpos($schema,'public static function required_tables')&&false!==strpos($schema,"'reviews','integrity_actions','research','dataset_access','events','outbox','idempotency'")&&false!==strpos($schema,'public static function schema_complete')&&false!==strpos($schema,"'schema_complete' => \$complete")&&false!==strpos($schema,"return self::schema_complete() ? 'active' : 'degraded'"),'health/runtime can still report active while required core tables are absent');
v2415_ok(12,false!==strpos($schema,"'posts_per_page' => 200")&&false!==strpos($schema,"'paged' => \$page")&&false!==strpos($schema,'do {')&&false!==strpos($schema,'while ( 200 === $count )'),'legacy migration still permanently stops after its first 200 entries');
v2415_ok(13,false!==strpos($schema,'legacy_migration_projection_failed')&&false!==strpos($schema,'if ( ! HE_V2_Domain::ensure_concept_for_post( $post_id ) )')&&strpos($schema,'legacy_migration_projection_failed')<strpos($schema,"update_option( 'he_v2_legacy_migrated'"),'legacy migration can still mark complete after a failed canonical projection');
v2415_ok(14,false!==strpos($domain,"\$failed = array()")&&false!==strpos($domain,'reindex_all_failed')&&false!==strpos($domain,"new WP_Error( 'he_reindex_failed'")&&false!==strpos($domain,"'failed_count' => count( \$failed )"),'bulk reindex still reports success despite individual failures');
v2415_ok(15,''!==$repair&&false!==strpos($repair,'repair_verification_failed')&&false!==strpos($repair,'is_wp_error( $reindexed )')&&false!==strpos($repair,'if ( ! self::schema_complete() )')&&strpos($repair,'delete_option( self::OPTION_FAILURE )')>strpos($repair,'if ( ! self::schema_complete() )')&&false!==strpos($repair,'delete_option( self::OPTION_SAFE_MODE )')&&false!==strpos($repair,"'active' !== \$after['status']")&&false!==strpos($repair,'repair_final_health_failed'),'repair can still clear failure/safe mode before verified schema/index health or skip final active-health verification');
v2415_ok(16,false!==strpos($domain,'entry_projection_transaction_start_failed')&&false!==strpos($domain,'canonical-alias-failed')&&false!==strpos($domain,'published-baseline-snapshot-failed')&&false!==strpos($domain,'published-baseline-finalize-failed')&&false!==strpos($domain,'entry_projection_create_failed'),'new concept projection child writes/commit are still not fail-closed');
v2415_ok(17,false!==strpos($domain,'public static function concept_by_post_id')&&substr_count($public,'HE_V2_Domain::concept_by_post_id')>=2&&false===strpos($public,'HE_V2_Domain::concept_by_id( $post->post_name'),'singular entry rendering/redirect still binds to mutable post_name instead of authoritative post_id');
if($upto>=18){preg_match('/public static function publish_due\(\).*?\n\t\}/s',$domain,$m);$legacy=$m[0]??'';preg_match('/public static function maintenance\(\).*?\n\t\}/s',$domain,$n);$maint=$n[0]??'';v2415_ok(18,false!==strpos($legacy,'HE_V22_Schedule::publish_due_securely')&&false===strpos($legacy,"UPDATE {\$table} SET status='published'")&&false===strpos($maint,'self::publish_due()'),'unsafe duplicate legacy scheduled publisher still exists in maintenance');}
v2415_ok(19,false!==strpos($domain,'encode_public_cursor')&&false!==strpos($schema,'schema_complete')&&false!==strpos($domain,'HE_V22_Schedule::publish_due_securely')&&false!==strpos($api,'he_canonical_public_id_required'),'round-19 corrected-state cross-cutting controls are incomplete');
v2415_ok(20,preg_match('/ \* Version: 2\.4\.(?:15|16|17|18|19)/',$bootstrap)&&preg_match("/HE_VERSION', '2\\.4\\.(?:15|16|17|18|19)/",$bootstrap)&&preg_match("/HE_CONTRACT_VERSION', '2\\.4\\.(?:15|16|17|18|19)/",$bootstrap)&&false!==strpos($bootstrap,"'future_hardening_version'=>")&&preg_match('/Stable tag: 2\.4\.(?:15|16|17|18|19)/',$readme)&&false!==strpos($runall,'v2415-sixteenth-twenty-round-regressions.php')&&preg_match('/All File 06 v2\.4\.(?:15|16|17|18|19) automated checks/',$runall),'historical v2.4.15 release controls do not tolerate the current v2.4.x candidate');

if($fail){fwrite(STDERR,"File 06 v2.4.15 sixteenth-review regressions FAILED:\n- ".implode("\n- ",$fail)."\n");exit(1);}echo "File 06 v2.4.15 sixteenth-review regressions through R{$upto}: PASS\n";
