<?php
defined( 'ABSPATH' ) || exit;
final class HE_Publishing {
	public function hooks() { add_shortcode( 'he_submit_entry', array( $this, 'form' ) ); add_action( 'admin_post_he_submit_entry', array( $this, 'submit' ) ); }
	public function form() { if ( ! is_user_logged_in() ) { return '<div class="he-notice"><p>An account is required to submit an entry.</p><a class="he-button" href="' . esc_url( wp_login_url( get_permalink() ) ) . '">Log In</a></div>'; } if ( ! HE_Permissions::can_submit() ) { return '<div class="he-notice"><strong>Entry publishing is restricted.</strong><p>Only the Founder, administrators, and verified doctors may submit encyclopedia entries.</p></div>'; } $entries = get_posts( array( 'post_type' => HE_Content::TYPE, 'post_status' => 'publish', 'posts_per_page' => 100, 'orderby' => 'title', 'order' => 'ASC' ) ); $books = post_type_exists( 'slc_book' ) ? get_posts( array( 'post_type' => 'slc_book', 'post_status' => 'publish', 'posts_per_page' => 100, 'orderby' => 'title', 'order' => 'ASC' ) ) : array(); $lessons = post_type_exists( 'slc_lesson' ) ? get_posts( array( 'post_type' => 'slc_lesson', 'post_status' => 'publish', 'posts_per_page' => 100, 'orderby' => 'title', 'order' => 'ASC' ) ) : array(); ob_start(); ?>
		<main class="he-shell"><header class="he-page-head"><span>Encyclopedia Editorial System</span><h1>Submit Encyclopedia Entry</h1><p>All content must be written in American English and supported by references.</p></header><form class="he-form" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" method="post" enctype="multipart/form-data"><input type="hidden" name="action" value="he_submit_entry"><?php wp_nonce_field( 'he_submit_entry', 'he_nonce' ); ?>
		<label>Entry title<input name="title" maxlength="180" required></label><label>Knowledge type<select name="knowledge_type" required><option value="">Select type</option><?php foreach ( HE_Content::types() as $slug => $name ) : ?><option value="<?php echo esc_attr( $slug ); ?>"><?php echo esc_html( $name ); ?></option><?php endforeach; ?></select></label><label class="he-full">Short definition or summary<textarea name="excerpt" rows="3" maxlength="500" required></textarea></label><label class="he-full">Complete educational entry<textarea name="content" rows="15" required></textarea></label>
		<?php foreach ( HE_Content::fields() as $key => $label ) : ?><label class="<?php echo in_array( $key, array( 'key_points', 'symptoms', 'causes', 'modalities', 'red_flags', 'safety', 'references' ), true ) ? 'he-full' : ''; ?>"><?php echo esc_html( $label ); ?><?php if ( in_array( $key, array( 'key_points', 'symptoms', 'causes', 'modalities', 'red_flags', 'safety', 'references' ), true ) ) : ?><textarea name="<?php echo esc_attr( $key ); ?>" rows="4"<?php echo 'references' === $key ? ' required' : ''; ?>></textarea><?php else : ?><input name="<?php echo esc_attr( $key ); ?>" maxlength="300"><?php endif; ?></label><?php endforeach; ?>
		<label>Featured image<input type="file" name="image" accept="image/jpeg,image/png,image/webp"><small>JPG, PNG, or WebP; maximum 5 MB.</small></label><label>Related entries<select name="related_ids[]" multiple size="6"><?php foreach ( $entries as $entry ) : ?><option value="<?php echo absint( $entry->ID ); ?>"><?php echo esc_html( $entry->post_title ); ?></option><?php endforeach; ?></select><small>Select up to five.</small></label>
		<?php if ( $books ) : ?><label>Related learning book<select name="book_id"><option value="0">None</option><?php foreach ( $books as $book ) : ?><option value="<?php echo absint( $book->ID ); ?>"><?php echo esc_html( $book->post_title ); ?></option><?php endforeach; ?></select></label><?php endif; ?><?php if ( $lessons ) : ?><label>Related lesson<select name="lesson_id"><option value="0">None</option><?php foreach ( $lessons as $lesson ) : ?><option value="<?php echo absint( $lesson->ID ); ?>"><?php echo esc_html( $lesson->post_title ); ?></option><?php endforeach; ?></select></label><?php endif; ?>
		<label class="he-check he-full"><input type="checkbox" name="english_confirm" value="1" required> I confirm that the entry is written completely in American English.</label><label class="he-check he-full"><input type="checkbox" name="medical_confirm" value="1" required> I confirm that this entry is educational, avoids cure guarantees and personal prescriptions, and does not delay emergency or qualified medical care.</label><button class="he-button" type="submit"><?php echo 'publish' === HE_Permissions::status() ? 'Publish Entry' : 'Submit for Review'; ?></button></form></main>
		<?php return ob_get_clean(); }
	public function submit() { if ( ! is_user_logged_in() || ! HE_Permissions::can_submit() ) { wp_die( esc_html__( 'You are not allowed to submit encyclopedia entries.', 'homeopathy-encyclopedia' ), '', array( 'response' => 403 ) ); } check_admin_referer( 'he_submit_entry', 'he_nonce' ); $title = isset( $_POST['title'] ) ? sanitize_text_field( wp_unslash( $_POST['title'] ) ) : ''; $excerpt = isset( $_POST['excerpt'] ) ? sanitize_textarea_field( wp_unslash( $_POST['excerpt'] ) ) : ''; $content = isset( $_POST['content'] ) ? wp_kses_post( wp_unslash( $_POST['content'] ) ) : ''; $type = isset( $_POST['knowledge_type'] ) ? sanitize_title( wp_unslash( $_POST['knowledge_type'] ) ) : ''; $refs = isset( $_POST['references'] ) ? sanitize_textarea_field( wp_unslash( $_POST['references'] ) ) : ''; $title = $this->limit( $title, 180 ); $excerpt = $this->limit( $excerpt, 500 ); if ( ! $title || ! trim( wp_strip_all_tags( $content ) ) || ! HE_Content::allowed( $type ) || ! trim( $refs ) || empty( $_POST['english_confirm'] ) || empty( $_POST['medical_confirm'] ) ) { $this->fail( 'Complete the title, content, approved knowledge type, references, and confirmations.' ); } if ( $this->non_latin_script( $title . ' ' . $excerpt . ' ' . wp_strip_all_tags( $content ) ) ) { $this->fail( 'This release accepts American English content only. Non-Latin writing was detected.' ); } $red = isset( $_POST['red_flags'] ) ? sanitize_textarea_field( wp_unslash( $_POST['red_flags'] ) ) : ''; $safety = isset( $_POST['safety'] ) ? sanitize_textarea_field( wp_unslash( $_POST['safety'] ) ) : ''; if ( in_array( $type, array( 'health-condition', 'pathology' ), true ) && ! trim( $red ) ) { $this->fail( 'Health Condition and Pathology entries require medical red flags.' ); } if ( 'remedy' === $type && ! trim( $safety ) ) { $this->fail( 'Remedy entries require safety and limitations.' ); } $error = $this->image_error(); if ( $error ) { $this->fail( $error ); }
		$status = HE_Permissions::status(); $id = wp_insert_post( array( 'post_type' => HE_Content::TYPE, 'post_status' => $status, 'post_author' => get_current_user_id(), 'post_title' => $title, 'post_excerpt' => $excerpt, 'post_content' => $content, 'comment_status' => 'open', 'ping_status' => 'closed' ), true ); if ( is_wp_error( $id ) ) { $this->fail( 'The entry could not be saved.' ); } if ( ! HE_Content::assign( $id, $type ) ) { wp_update_post( array( 'ID' => $id, 'post_status' => 'draft' ) ); $this->fail( 'The approved knowledge type could not be assigned.' ); }
		foreach ( HE_Content::fields() as $key => $label ) { $value = isset( $_POST[ $key ] ) ? wp_unslash( $_POST[ $key ] ) : ''; $value = in_array( $key, array( 'key_points', 'symptoms', 'causes', 'modalities', 'red_flags', 'safety', 'references' ), true ) ? sanitize_textarea_field( $value ) : sanitize_text_field( $value ); update_post_meta( $id, '_he_' . $key, $value ); }
		$related = isset( $_POST['related_ids'] ) ? array_slice( array_unique( array_map( 'absint', (array) wp_unslash( $_POST['related_ids'] ) ) ), 0, 5 ) : array(); $related = array_values( array_filter( $related, function( $related_id ) { return HE_Content::TYPE === get_post_type( $related_id ) && 'publish' === get_post_status( $related_id ); } ) ); update_post_meta( $id, '_he_related_ids', $related ); $book = isset( $_POST['book_id'] ) ? absint( $_POST['book_id'] ) : 0; $lesson = isset( $_POST['lesson_id'] ) ? absint( $_POST['lesson_id'] ) : 0; update_post_meta( $id, '_he_book_id', 'slc_book' === get_post_type( $book ) ? $book : 0 ); update_post_meta( $id, '_he_lesson_id', 'slc_lesson' === get_post_type( $lesson ) ? $lesson : 0 ); update_post_meta( $id, '_he_language', 'en-US' ); update_post_meta( $id, '_he_views', 0 ); $image = $this->upload( $id ); if ( $image ) { set_post_thumbnail( $id, $image ); } HE_Admin::audit( $id, 'publish' === $status ? 'published' : 'submitted', '' ); if ( 'publish' === $status ) { wp_safe_redirect( get_permalink( $id ) ); } else { $pages = (array) get_option( 'he_page_map', array() ); wp_safe_redirect( add_query_arg( 'submitted', '1', ! empty( $pages['submit'] ) ? get_permalink( $pages['submit'] ) : home_url( '/' ) ) ); } exit; }
	private function non_latin_script( $text ) { return (bool) preg_match( '/[\x{0600}-\x{06FF}\x{0750}-\x{077F}\x{0900}-\x{097F}\x{0400}-\x{04FF}\x{4E00}-\x{9FFF}\x{3040}-\x{30FF}]/u', $text ); }
	private function image_error() { if ( empty( $_FILES['image']['name'] ) ) { return ''; } $f = $_FILES['image']; if ( ! empty( $f['error'] ) || (int) $f['size'] > 5 * MB_IN_BYTES ) { return 'The image must upload successfully and be 5 MB or smaller.'; } $type = wp_check_filetype_and_ext( $f['tmp_name'], $f['name'], array( 'jpg|jpeg' => 'image/jpeg', 'png' => 'image/png', 'webp' => 'image/webp' ) ); return empty( $type['type'] ) ? 'Only JPG, PNG, and WebP images are allowed.' : ''; }
	private function upload( $id ) { if ( empty( $_FILES['image']['name'] ) ) { return 0; } require_once ABSPATH . 'wp-admin/includes/file.php'; require_once ABSPATH . 'wp-admin/includes/media.php'; require_once ABSPATH . 'wp-admin/includes/image.php'; $image = media_handle_upload( 'image', $id, array(), array( 'test_form' => false, 'mimes' => array( 'jpg|jpeg' => 'image/jpeg', 'png' => 'image/png', 'webp' => 'image/webp' ) ) ); return is_wp_error( $image ) ? 0 : absint( $image ); }
	private function limit( $text, $length ) { return function_exists( 'mb_substr' ) ? mb_substr( $text, 0, $length ) : substr( $text, 0, $length ); }
	private function fail( $message ) { wp_die( esc_html( $message ), esc_html__( 'Entry not accepted', 'homeopathy-encyclopedia' ), array( 'response' => 400, 'back_link' => true ) ); }
}

