<?php
/** File 06 Future Knowledge Intelligence: F06-FUT-001..018. */
defined( 'ABSPATH' ) || exit;

final class HE_V23_Future_Intelligence {
    const DB_VERSION = 1;
    const OPTION_DB_VERSION = 'he_v23_future_db_version';
    const CRON_HOOK = 'he_v23_evidence_watch';
    const NS = 'sabri/v2/file-06/future';

    public static function hooks() {
        add_action( 'rest_api_init', array( __CLASS__, 'routes' ) );
        add_action( self::CRON_HOOK, array( __CLASS__, 'scheduled_evidence_watch' ) );
        add_filter( 'sabri_notification_event_catalog', array( __CLASS__, 'notification_events' ) );
        add_filter( 'sabri_platform_contracts', array( __CLASS__, 'extend_contract' ), 120 );
        add_filter( 'sabri_publishing_dashboard_providers', array( __CLASS__, 'dashboard_projection' ), 120 );
        add_action( 'EncyclopediaEntryPublished.v1', array( __CLASS__, 'on_native_change' ), 10, 2 );
        add_action( 'EncyclopediaEntryCorrected.v1', array( __CLASS__, 'on_native_change' ), 10, 2 );
        add_action( 'EncyclopediaEntryRetracted.v1', array( __CLASS__, 'on_native_change' ), 10, 2 );
        add_action( 'KnowledgeConceptMerged.v1', array( __CLASS__, 'on_native_change' ), 10, 2 );
        if ( ! wp_next_scheduled( self::CRON_HOOK ) ) {
            wp_schedule_event( time() + HOUR_IN_SECONDS, 'daily', self::CRON_HOOK );
        }
    }

    public static function activate() {
        self::install_schema();
        if ( ! wp_next_scheduled( self::CRON_HOOK ) ) {
            wp_schedule_event( time() + HOUR_IN_SECONDS, 'daily', self::CRON_HOOK );
        }
    }

    public static function deactivate() {
        $timestamp = wp_next_scheduled( self::CRON_HOOK );
        if ( $timestamp ) { wp_unschedule_event( $timestamp, self::CRON_HOOK ); }
    }

    private static function table( $suffix ) { global $wpdb; return $wpdb->prefix . 'he_' . $suffix; }

    public static function install_schema() {
        global $wpdb;
        require_once ABSPATH . 'wp-admin/includes/upgrade.php';
        $charset = $wpdb->get_charset_collate();
        $claims = self::table( 'claims' );
        $prov = self::table( 'provenance' );
        $external = self::table( 'external_links' );
        $translations = self::table( 'translations' );
        $watches = self::table( 'watches' );
        $impact = self::table( 'impact_queue' );
        $gaps = self::table( 'evidence_gaps' );
        dbDelta( "CREATE TABLE {$claims} ( id bigint unsigned NOT NULL AUTO_INCREMENT, public_id char(36) NOT NULL, concept_id bigint unsigned NOT NULL, version_no int unsigned NOT NULL DEFAULT 0, claim_text longtext NOT NULL, claim_type varchar(40) NOT NULL DEFAULT 'factual', evidence_state varchar(24) NOT NULL DEFAULT 'uncertain', confidence decimal(5,4) NOT NULL DEFAULT 0, content_hash char(64) NOT NULL, status varchar(24) NOT NULL DEFAULT 'draft', created_by bigint unsigned NOT NULL DEFAULT 0, reviewed_by bigint unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY public_id (public_id), KEY concept_version (concept_id,version_no), KEY state_status (evidence_state,status), KEY content_hash (content_hash) ) {$charset};" );
        dbDelta( "CREATE TABLE {$prov} ( id bigint unsigned NOT NULL AUTO_INCREMENT, object_type varchar(32) NOT NULL, object_id varchar(80) NOT NULL, action varchar(48) NOT NULL, actor_id bigint unsigned NOT NULL DEFAULT 0, source_uri text NULL, source_identifier varchar(190) NULL, source_type varchar(48) NULL, transform varchar(80) NULL, parent_hash char(64) NULL, record_hash char(64) NOT NULL, payload_json longtext NULL, created_at datetime NOT NULL, PRIMARY KEY (id), KEY object_lookup (object_type,object_id), KEY source_identifier (source_identifier), KEY record_hash (record_hash) ) {$charset};" );
        dbDelta( "CREATE TABLE {$external} ( id bigint unsigned NOT NULL AUTO_INCREMENT, object_type varchar(32) NOT NULL, object_id varchar(80) NOT NULL, provider varchar(32) NOT NULL, external_id varchar(190) NOT NULL, relation varchar(40) NOT NULL DEFAULT 'related', metadata_json longtext NULL, status varchar(32) NOT NULL DEFAULT 'active', last_checked_at datetime NULL, next_check_at datetime NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY provider_external_object (provider,external_id,object_type,object_id), KEY watch_due (status,next_check_at), KEY object_lookup (object_type,object_id) ) {$charset};" );
        dbDelta( "CREATE TABLE {$translations} ( id bigint unsigned NOT NULL AUTO_INCREMENT, concept_id bigint unsigned NOT NULL, source_language varchar(16) NOT NULL, target_language varchar(16) NOT NULL, source_version int unsigned NOT NULL DEFAULT 0, translation_version int unsigned NOT NULL DEFAULT 1, content_json longtext NOT NULL, status varchar(28) NOT NULL DEFAULT 'draft', machine_assisted tinyint(1) NOT NULL DEFAULT 0, translator_id bigint unsigned NOT NULL DEFAULT 0, reviewer_id bigint unsigned NOT NULL DEFAULT 0, content_hash char(64) NOT NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY concept_language_version (concept_id,target_language,translation_version), KEY outdated (concept_id,source_version,status), KEY content_hash (content_hash) ) {$charset};" );
        dbDelta( "CREATE TABLE {$watches} ( id bigint unsigned NOT NULL AUTO_INCREMENT, user_id bigint unsigned NOT NULL, object_type varchar(32) NOT NULL, object_id varchar(80) NOT NULL, event_mask varchar(190) NOT NULL DEFAULT 'updated,corrected,retracted', created_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY user_object (user_id,object_type,object_id), KEY object_lookup (object_type,object_id) ) {$charset};" );
        dbDelta( "CREATE TABLE {$impact} ( id bigint unsigned NOT NULL AUTO_INCREMENT, source_type varchar(32) NOT NULL, source_id varchar(80) NOT NULL, source_event varchar(64) NOT NULL, consumer_file varchar(24) NOT NULL, consumer_ref varchar(190) NULL, state varchar(24) NOT NULL DEFAULT 'pending', reason varchar(190) NULL, attempts smallint unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), KEY pending_consumer (state,consumer_file), KEY source_lookup (source_type,source_id) ) {$charset};" );
        dbDelta( "CREATE TABLE {$gaps} ( id bigint unsigned NOT NULL AUTO_INCREMENT, concept_id bigint unsigned NOT NULL, gap_type varchar(40) NOT NULL, severity varchar(16) NOT NULL DEFAULT 'medium', state varchar(24) NOT NULL DEFAULT 'open', detail_json longtext NULL, detected_at datetime NOT NULL, resolved_at datetime NULL, PRIMARY KEY (id), UNIQUE KEY concept_gap (concept_id,gap_type), KEY state_severity (state,severity) ) {$charset};" );
        update_option( self::OPTION_DB_VERSION, self::DB_VERSION, false );
    }

    private static function now() { return current_time( 'mysql', true ); }
    private static function json( $value ) { return wp_json_encode( $value, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ); }
    private static function decode( $json ) { $v = json_decode( (string) $json, true ); return is_array( $v ) ? $v : array(); }
    private static function clean_id( $value ) { return substr( sanitize_text_field( (string) $value ), 0, 190 ); }
    private static function uuid() { return function_exists( 'wp_generate_uuid4' ) ? wp_generate_uuid4() : uniqid( 'he-', true ); }
    private static function hash( $value ) { return hash( 'sha256', is_string( $value ) ? $value : self::json( $value ) ); }
    private static function concept( $id ) { $row = HE_V2_Domain::concept_by_id( $id, true ); if ( ! $row && ctype_digit( (string) $id ) ) { $row = HE_V2_Domain::concept_by_id( absint( $id ), true ); } return $row; }
    private static function editorial_permission( $cap = null ) { return HE_V2_Auth::rest_permission( $cap ?: HE_V2_Auth::CAP_EDIT ); }

    public static function routes() {
        $read = '__return_true';
        register_rest_route( self::NS, '/claims', array( array( 'methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'claims_list'),'permission_callback'=>$read ), array( 'methods'=>WP_REST_Server::CREATABLE,'callback'=>array(__CLASS__,'claims_create'),'permission_callback'=>array(__CLASS__,'can_edit') ) ) );
        register_rest_route( self::NS, '/claims/(?P<id>[a-zA-Z0-9\-]+)', array( 'methods'=>WP_REST_Server::EDITABLE,'callback'=>array(__CLASS__,'claims_update'),'permission_callback'=>array(__CLASS__,'can_review') ) );
        register_rest_route( self::NS, '/provenance/(?P<type>[a-z0-9\-]+)/(?P<id>[a-zA-Z0-9\-:]+)', array( 'methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'provenance_get'),'permission_callback'=>$read ) );
        register_rest_route( self::NS, '/external', array( 'methods'=>WP_REST_Server::CREATABLE,'callback'=>array(__CLASS__,'external_link'),'permission_callback'=>array(__CLASS__,'can_research') ) );
        register_rest_route( self::NS, '/external/sync', array( 'methods'=>WP_REST_Server::CREATABLE,'callback'=>array(__CLASS__,'external_sync'),'permission_callback'=>array(__CLASS__,'can_research') ) );
        register_rest_route( self::NS, '/semantic-duplicates/(?P<concept>[a-zA-Z0-9\-]+)', array( 'methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'semantic_duplicates'),'permission_callback'=>array(__CLASS__,'can_review') ) );
        register_rest_route( self::NS, '/graph/(?P<concept>[a-zA-Z0-9\-]+)', array( 'methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'graph'),'permission_callback'=>$read ) );
        register_rest_route( self::NS, '/time-machine/(?P<concept>[a-zA-Z0-9\-]+)', array( 'methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'time_machine'),'permission_callback'=>$read ) );
        register_rest_route( self::NS, '/impact/(?P<concept>[a-zA-Z0-9\-]+)', array( 'methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'impact'),'permission_callback'=>array(__CLASS__,'can_review') ) );
        register_rest_route( self::NS, '/freshness/(?P<concept>[a-zA-Z0-9\-]+)', array( 'methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'freshness'),'permission_callback'=>$read ) );
        register_rest_route( self::NS, '/gaps', array( 'methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'gaps'),'permission_callback'=>array(__CLASS__,'can_review') ) );
        register_rest_route( self::NS, '/citations/(?P<concept>[a-zA-Z0-9\-]+)', array( 'methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'citations'),'permission_callback'=>$read ) );
        register_rest_route( self::NS, '/watch', array( array( 'methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'watch_list'),'permission_callback'=>array(__CLASS__,'can_member') ), array( 'methods'=>WP_REST_Server::CREATABLE,'callback'=>array(__CLASS__,'watch_add'),'permission_callback'=>array(__CLASS__,'can_member') ), array( 'methods'=>WP_REST_Server::DELETABLE,'callback'=>array(__CLASS__,'watch_delete'),'permission_callback'=>array(__CLASS__,'can_member') ) ) );
        register_rest_route( self::NS, '/translations', array( array( 'methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'translation_list'),'permission_callback'=>$read ), array( 'methods'=>WP_REST_Server::CREATABLE,'callback'=>array(__CLASS__,'translation_save'),'permission_callback'=>array(__CLASS__,'can_edit') ) ) );
        register_rest_route( self::NS, '/command-center', array( 'methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'command_center'),'permission_callback'=>array(__CLASS__,'can_review') ) );
    }

    public static function can_edit() { return self::editorial_permission( HE_V2_Auth::CAP_EDIT ); }
    public static function can_review() { return self::editorial_permission( HE_V2_Auth::CAP_REVIEW ); }
    public static function can_research() { return self::editorial_permission( HE_V2_Auth::CAP_RESEARCH ); }
    public static function can_member() { if ( ! is_user_logged_in() || ! HE_V2_Auth::provider_ready() || ! HE_V2_Auth::membership_allowed() ) { return new WP_Error( 'he_future_forbidden', __( 'An eligible signed-in account is required.', 'homeopathy-encyclopedia' ), array( 'status'=>403 ) ); } return true; }

    /* F06-FUT-001 Claim-Level Evidence Graph. */
    public static function claims_list( WP_REST_Request $request ) { global $wpdb; $concept=self::concept($request->get_param('concept')); if(!$concept){return new WP_Error('he_not_found','Concept not found.',array('status'=>404));} $rows=$wpdb->get_results($wpdb->prepare("SELECT public_id,claim_text,claim_type,evidence_state,confidence,status,updated_at FROM ".self::table('claims')." WHERE concept_id=%d AND status='published' ORDER BY id ASC",(int)$concept['id']),ARRAY_A); return rest_ensure_response(array('concept_id'=>$concept['public_id'],'claims'=>$rows)); }
    public static function claims_create( WP_REST_Request $request ) { global $wpdb; $concept=self::concept($request->get_param('concept')); $text=trim(wp_kses_post((string)$request->get_param('claim_text'))); if(!$concept||''===$text){return new WP_Error('he_invalid_claim','Concept and claim text are required.',array('status'=>400));} $id=self::uuid();$now=self::now();$wpdb->insert(self::table('claims'),array('public_id'=>$id,'concept_id'=>(int)$concept['id'],'version_no'=>(int)$concept['current_version'],'claim_text'=>$text,'claim_type'=>sanitize_key($request->get_param('claim_type')?:'factual'),'evidence_state'=>'uncertain','confidence'=>0,'content_hash'=>self::hash($text),'status'=>'draft','created_by'=>get_current_user_id(),'created_at'=>$now,'updated_at'=>$now));self::provenance('claim',$id,'created',array('concept'=>$concept['public_id'],'content_hash'=>self::hash($text)));return rest_ensure_response(array('id'=>$id,'status'=>'draft')); }
    public static function claims_update( WP_REST_Request $request ) { global $wpdb;$id=self::clean_id($request['id']);$table=self::table('claims');$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$table} WHERE public_id=%s",$id),ARRAY_A);if(!$row){return new WP_Error('he_not_found','Claim not found.',array('status'=>404));}$state=sanitize_key($request->get_param('evidence_state')?:$row['evidence_state']);if(!in_array($state,array('supporting','contradicting','mixed','uncertain','historical'),true)){return new WP_Error('he_invalid_evidence_state','Invalid evidence state.',array('status'=>400));}$status=sanitize_key($request->get_param('status')?:$row['status']);if(!in_array($status,array('draft','review','published','superseded','retracted'),true)){return new WP_Error('he_invalid_claim_status','Invalid claim status.',array('status'=>400));}$confidence=min(1,max(0,(float)$request->get_param('confidence')));$wpdb->update($table,array('evidence_state'=>$state,'status'=>$status,'confidence'=>$confidence,'reviewed_by'=>get_current_user_id(),'updated_at'=>self::now()),array('id'=>(int)$row['id']));self::provenance('claim',$id,'reviewed',array('evidence_state'=>$state,'status'=>$status,'confidence'=>$confidence));return rest_ensure_response(array('id'=>$id,'status'=>$status,'evidence_state'=>$state,'confidence'=>$confidence)); }

    /* F06-FUT-002 Universal Provenance Ledger. */
    private static function provenance($type,$id,$action,$payload=array(),$source=array()){global $wpdb;$table=self::table('provenance');$previous=$wpdb->get_var($wpdb->prepare("SELECT record_hash FROM {$table} WHERE object_type=%s AND object_id=%s ORDER BY id DESC LIMIT 1",$type,(string)$id));$record=array('type'=>$type,'id'=>(string)$id,'action'=>$action,'actor'=>get_current_user_id(),'payload'=>$payload,'source'=>$source,'parent'=>$previous?:'','at'=>self::now());$hash=self::hash($record);$wpdb->insert($table,array('object_type'=>sanitize_key($type),'object_id'=>self::clean_id($id),'action'=>sanitize_key($action),'actor_id'=>get_current_user_id(),'source_uri'=>isset($source['uri'])?esc_url_raw($source['uri']):'','source_identifier'=>isset($source['identifier'])?self::clean_id($source['identifier']):'','source_type'=>isset($source['type'])?sanitize_key($source['type']):'','transform'=>isset($source['transform'])?sanitize_text_field($source['transform']):'','parent_hash'=>$previous?:'','record_hash'=>$hash,'payload_json'=>self::json($payload),'created_at'=>self::now()));return $hash;}
    public static function provenance_get(WP_REST_Request $request){global $wpdb;$type=sanitize_key($request['type']);$id=self::clean_id($request['id']);$rows=$wpdb->get_results($wpdb->prepare("SELECT action,source_uri,source_identifier,source_type,transform,parent_hash,record_hash,created_at FROM ".self::table('provenance')." WHERE object_type=%s AND object_id=%s ORDER BY id ASC LIMIT 500",$type,$id),ARRAY_A);return rest_ensure_response(array('object_type'=>$type,'object_id'=>$id,'records'=>$rows,'format'=>'provenance-ledger-v1','prov_o_compatible'=>true));}

    /* F06-FUT-003..008 Crossref/PubMed/ClinicalTrials/ORCID/DataCite/MeSH adapters. */
    public static function external_link(WP_REST_Request $request){global $wpdb;$provider=sanitize_key($request->get_param('provider'));if(!in_array($provider,array('crossref','pubmed','clinicaltrials','orcid','datacite','mesh'),true)){return new WP_Error('he_provider_invalid','Unsupported provider.',array('status'=>400));}$object_type=sanitize_key($request->get_param('object_type')?:'concept');$object_id=self::clean_id($request->get_param('object_id'));$external_id=self::clean_id($request->get_param('external_id'));if(!$object_id||!$external_id){return new WP_Error('he_external_invalid','Object and external ID are required.',array('status'=>400));}$now=self::now();$table=self::table('external_links');$wpdb->replace($table,array('object_type'=>$object_type,'object_id'=>$object_id,'provider'=>$provider,'external_id'=>$external_id,'relation'=>sanitize_key($request->get_param('relation')?:'related'),'metadata_json'=>self::json(array()),'status'=>'active','last_checked_at'=>null,'next_check_at'=>gmdate('Y-m-d H:i:s',time()+DAY_IN_SECONDS),'created_at'=>$now,'updated_at'=>$now));self::provenance($object_type,$object_id,'external-linked',array('provider'=>$provider,'external_id'=>$external_id));return self::sync_external_row((int)$wpdb->insert_id);}
    public static function external_sync(WP_REST_Request $request){global $wpdb;$id=absint($request->get_param('id'));if($id){return self::sync_external_row($id);}$rows=$wpdb->get_col("SELECT id FROM ".self::table('external_links')." WHERE status IN ('active','review-required') ORDER BY COALESCE(next_check_at,'1970-01-01') ASC LIMIT 25");$out=array();foreach($rows as $row_id){$out[]=self::sync_external_row((int)$row_id);}return rest_ensure_response(array('processed'=>count($out),'results'=>$out));}
    private static function sync_external_row($id){global $wpdb;$table=self::table('external_links');$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$table} WHERE id=%d",$id),ARRAY_A);if(!$row){return new WP_Error('he_external_not_found','External link not found.',array('status'=>404));}$result=apply_filters('he_future_external_lookup',null,$row['provider'],$row['external_id'],array('object_type'=>$row['object_type'],'object_id'=>$row['object_id']));if(is_wp_error($result)){$wpdb->update($table,array('status'=>'provider-error','last_checked_at'=>self::now(),'next_check_at'=>gmdate('Y-m-d H:i:s',time()+DAY_IN_SECONDS),'updated_at'=>self::now()),array('id'=>$id));return $result;}if(!is_array($result)){$result=array('available'=>false,'provider_unconfigured'=>true);}$integrity=sanitize_key($result['integrity_state']??'active');$status=in_array($integrity,array('retracted','corrected','expression-of-concern'),true)?'review-required':'active';$wpdb->update($table,array('metadata_json'=>self::json(self::public_external_metadata($result)),'status'=>$status,'last_checked_at'=>self::now(),'next_check_at'=>gmdate('Y-m-d H:i:s',time()+7*DAY_IN_SECONDS),'updated_at'=>self::now()),array('id'=>$id));self::provenance($row['object_type'],$row['object_id'],'external-synced',array('provider'=>$row['provider'],'external_id'=>$row['external_id'],'integrity_state'=>$integrity));if('review-required'===$status){self::emit('KnowledgeEvidenceReviewRequired.v1',array('object_type'=>$row['object_type'],'object_id'=>$row['object_id'],'provider'=>$row['provider'],'external_id'=>$row['external_id'],'integrity_state'=>$integrity));}return rest_ensure_response(array('id'=>$id,'provider'=>$row['provider'],'status'=>$status,'metadata'=>self::public_external_metadata($result)));}
    private static function public_external_metadata($data){$allow=array('title','authors','published_at','updated_at','url','doi','pmid','nct_id','orcid','datacite_doi','mesh_id','study_status','study_type','integrity_state','license','source');return array_intersect_key(is_array($data)?$data:array(),array_flip($allow));}
    public static function scheduled_evidence_watch(){global $wpdb;$ids=$wpdb->get_col($wpdb->prepare("SELECT id FROM ".self::table('external_links')." WHERE status IN ('active','review-required','provider-error') AND (next_check_at IS NULL OR next_check_at<=%s) ORDER BY id ASC LIMIT 50",self::now()));foreach($ids as $id){self::sync_external_row((int)$id);}self::scan_gaps();}

    /* F06-FUT-009 Semantic duplicate intelligence; advisory only. */
    public static function semantic_duplicates(WP_REST_Request $request){global $wpdb;$concept=self::concept($request['concept']);if(!$concept){return new WP_Error('he_not_found','Concept not found.',array('status'=>404));}$search=self::normalize_text(($concept['canonical_name']??'').' '.($concept['summary']??''));$rows=$wpdb->get_results($wpdb->prepare("SELECT id,public_id,canonical_name,summary,status FROM ".HE_V2_Schema::table('concepts')." WHERE id<>%d AND status NOT IN ('merged','retracted') ORDER BY updated_at DESC LIMIT 250",(int)$concept['id']),ARRAY_A);$scores=array();foreach($rows as $row){$candidate=self::normalize_text($row['canonical_name'].' '.$row['summary']);similar_text($search,$candidate,$pct);if($pct>=35){$scores[]=array('id'=>$row['public_id'],'title'=>$row['canonical_name'],'score'=>round($pct/100,4),'decision'=>'human-review-required');}}usort($scores,static function($a,$b){return $b['score']<=>$a['score'];});return rest_ensure_response(array('concept'=>$concept['public_id'],'candidates'=>array_slice($scores,0,20),'auto_merge'=>false));}
    private static function normalize_text($text){return trim(preg_replace('/\s+/u',' ',mb_strtolower(wp_strip_all_tags((string)$text))));}

    /* F06-FUT-010 Graph Explorer data; visual rendering remains File 25-owned. */
    public static function graph(WP_REST_Request $request){$concept=self::concept($request['concept']);if(!$concept){return new WP_Error('he_not_found','Concept not found.',array('status'=>404));}$related=HE_V2_Domain::get_related_graph($concept['public_id']);global $wpdb;$claims=$wpdb->get_results($wpdb->prepare("SELECT public_id,claim_text,evidence_state,confidence FROM ".self::table('claims')." WHERE concept_id=%d AND status='published' ORDER BY id ASC LIMIT 100",(int)$concept['id']),ARRAY_A);$external=$wpdb->get_results($wpdb->prepare("SELECT provider,external_id,relation,status FROM ".self::table('external_links')." WHERE object_type='concept' AND object_id=%s ORDER BY id ASC LIMIT 100",$concept['public_id']),ARRAY_A);return rest_ensure_response(array('owner'=>'file-06','presentation_owner'=>'file-25','concept'=>$concept['public_id'],'relations'=>$related,'claims'=>$claims,'external_evidence'=>$external));}

    /* F06-FUT-011 Knowledge Time Machine. */
    public static function time_machine(WP_REST_Request $request){global $wpdb;$concept=self::concept($request['concept']);if(!$concept){return new WP_Error('he_not_found','Concept not found.',array('status'=>404));}$table=HE_V2_Schema::table('versions');$at=sanitize_text_field($request->get_param('at')?:'');$where=$at?$wpdb->prepare(' AND created_at<=%s',$at):'';$rows=$wpdb->get_results($wpdb->prepare("SELECT version_no,state,content_hash,created_by,created_at FROM {$table} WHERE concept_id=%d",(int)$concept['id']).$where.' ORDER BY version_no DESC LIMIT 100',ARRAY_A);return rest_ensure_response(array('concept'=>$concept['public_id'],'as_of'=>$at?:null,'versions'=>$rows));}

    /* F06-FUT-012 Cross-platform impact propagation. */
    public static function on_native_change($payload=array(),$context=array()){$id=is_array($payload)?($payload['public_id']??$payload['id']??''):'';if(!$id){return;}$event=current_action();self::queue_impact('concept',$id,$event);self::mark_translations_outdated($id);self::notify_watchers('concept',$id,$event);}
    private static function queue_impact($type,$id,$event){global $wpdb;$now=self::now();foreach(array('file-05','file-12','file-15','file-16','file-21','file-26') as $consumer){$wpdb->insert(self::table('impact_queue'),array('source_type'=>$type,'source_id'=>self::clean_id($id),'source_event'=>sanitize_key($event),'consumer_file'=>$consumer,'state'=>'pending','reason'=>'canonical-knowledge-changed','created_at'=>$now,'updated_at'=>$now));}self::emit('KnowledgeImpactReviewRequested.v1',array('source_type'=>$type,'source_id'=>$id,'event'=>$event));}
    public static function impact(WP_REST_Request $request){global $wpdb;$id=self::clean_id($request['concept']);$rows=$wpdb->get_results($wpdb->prepare("SELECT consumer_file,consumer_ref,state,reason,attempts,updated_at FROM ".self::table('impact_queue')." WHERE source_id=%s ORDER BY id DESC LIMIT 200",$id),ARRAY_A);return rest_ensure_response(array('source_id'=>$id,'items'=>$rows));}

    /* F06-FUT-013 Living Knowledge Freshness Engine. */
    public static function freshness(WP_REST_Request $request){$concept=self::concept($request['concept']);if(!$concept){return new WP_Error('he_not_found','Concept not found.',array('status'=>404));}return rest_ensure_response(self::freshness_for($concept));}
    private static function freshness_for($concept){global $wpdb;$last_review=$wpdb->get_var($wpdb->prepare("SELECT MAX(created_at) FROM ".HE_V2_Schema::table('reviews')." WHERE concept_id=%d AND decision='approved'",(int)$concept['id']));$last_scan=$wpdb->get_var($wpdb->prepare("SELECT MAX(last_checked_at) FROM ".self::table('external_links')." WHERE object_type='concept' AND object_id=%s",$concept['public_id']));$risk=in_array(($concept['safety_status']??''),array('red-flag','high-risk'),true)?'high':'normal';$days='high'===$risk?90:365;$base=$last_review?:($concept['updated_at']??self::now());$due=gmdate('c',strtotime($base.' +'.$days.' days'));$state=time()>strtotime($due)?'review-due':'current';if($last_scan&&time()-strtotime($last_scan)>180*DAY_IN_SECONDS){$state='stale';}return array('concept'=>$concept['public_id'],'last_human_review'=>$last_review,'last_evidence_scan'=>$last_scan,'review_due_at'=>$due,'freshness_state'=>$state,'risk_band'=>$risk);}

    /* F06-FUT-014 Evidence-Gap and Research-Priority Radar. */
    private static function scan_gaps(){global $wpdb;$concepts=$wpdb->get_results("SELECT id,public_id,status,current_version FROM ".HE_V2_Schema::table('concepts')." WHERE status IN ('published','corrected') ORDER BY id ASC LIMIT 500",ARRAY_A);foreach($concepts as $c){$refs=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM ".HE_V2_Schema::table('references')." WHERE concept_id=%d",(int)$c['id']));$claims=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM ".self::table('claims')." WHERE concept_id=%d AND status='published'",(int)$c['id']));$gap='';$sev='medium';if($refs<1){$gap='missing-references';$sev='high';}elseif($claims<1){$gap='claim-coverage';}if($gap){$wpdb->replace(self::table('evidence_gaps'),array('concept_id'=>(int)$c['id'],'gap_type'=>$gap,'severity'=>$sev,'state'=>'open','detail_json'=>self::json(array('references'=>$refs,'claims'=>$claims)),'detected_at'=>self::now()));}}}
    public static function gaps(WP_REST_Request $request){global $wpdb;self::scan_gaps();$rows=$wpdb->get_results("SELECT g.id,c.public_id,c.canonical_name,g.gap_type,g.severity,g.state,g.detected_at FROM ".self::table('evidence_gaps')." g INNER JOIN ".HE_V2_Schema::table('concepts')." c ON c.id=g.concept_id WHERE g.state='open' ORDER BY FIELD(g.severity,'critical','high','medium','low'),g.detected_at ASC LIMIT 250",ARRAY_A);return rest_ensure_response(array('items'=>$rows,'research_priority'=>'human-governed'));}

    /* F06-FUT-015 Citation Laboratory. */
    public static function citations(WP_REST_Request $request){global $wpdb;$concept=self::concept($request['concept']);if(!$concept){return new WP_Error('he_not_found','Concept not found.',array('status'=>404));}$refs=$wpdb->get_results($wpdb->prepare("SELECT * FROM ".HE_V2_Schema::table('references')." WHERE concept_id=%d ORDER BY id ASC LIMIT 500",(int)$concept['id']),ARRAY_A);$format=sanitize_key($request->get_param('format')?:'csl-json');$items=array();foreach($refs as $r){$meta=self::decode($r['metadata_json']??'');$item=array('id'=>$r['public_id']??('ref-'.$r['id']),'title'=>$meta['title']??($r['title']??''),'author'=>$meta['authors']??array(),'issued'=>$meta['issued']??($r['published_at']??''),'DOI'=>$meta['doi']??($r['doi']??''),'URL'=>$meta['url']??($r['url']??''),'type'=>'article');$items[]=$item;}if('bibtex'===$format){$text='';foreach($items as $i){$key=preg_replace('/[^A-Za-z0-9]/','',$i['id']);$text.="@article{{$key},\n  title={".str_replace(array('{','}'),'',$i['title'])."},\n  doi={".$i['DOI']."},\n  url={".$i['URL']."}\n}\n";}return new WP_REST_Response($text,200,array('Content-Type'=>'text/plain; charset=utf-8'));}if('ris'===$format){$text='';foreach($items as $i){$text.="TY  - JOUR\nTI  - {$i['title']}\nDO  - {$i['DOI']}\nUR  - {$i['URL']}\nER  - \n";}return new WP_REST_Response($text,200,array('Content-Type'=>'text/plain; charset=utf-8'));}return rest_ensure_response(array('format'=>'csl-json','items'=>$items,'json_ld'=>array('@context'=>'https://schema.org','@type'=>'CreativeWork','name'=>$concept['canonical_name'],'citation'=>$items)));}

    /* F06-FUT-016 Knowledge Watchlists; File 19 owns delivery. */
    public static function watch_list(){global $wpdb;$rows=$wpdb->get_results($wpdb->prepare("SELECT object_type,object_id,event_mask,created_at FROM ".self::table('watches')." WHERE user_id=%d ORDER BY id DESC",get_current_user_id()),ARRAY_A);return rest_ensure_response(array('items'=>$rows,'delivery_owner'=>'file-19'));}
    public static function watch_add(WP_REST_Request $request){global $wpdb;$type=sanitize_key($request->get_param('object_type')?:'concept');$id=self::clean_id($request->get_param('object_id'));if(!$id){return new WP_Error('he_watch_invalid','Object is required.',array('status'=>400));}$wpdb->replace(self::table('watches'),array('user_id'=>get_current_user_id(),'object_type'=>$type,'object_id'=>$id,'event_mask'=>'updated,corrected,retracted','created_at'=>self::now()));return rest_ensure_response(array('watched'=>true,'object_type'=>$type,'object_id'=>$id));}
    public static function watch_delete(WP_REST_Request $request){global $wpdb;$wpdb->delete(self::table('watches'),array('user_id'=>get_current_user_id(),'object_type'=>sanitize_key($request->get_param('object_type')?:'concept'),'object_id'=>self::clean_id($request->get_param('object_id'))));return rest_ensure_response(array('watched'=>false));}
    private static function notify_watchers($type,$id,$event){global $wpdb;$users=$wpdb->get_col($wpdb->prepare("SELECT user_id FROM ".self::table('watches')." WHERE object_type=%s AND object_id=%s",$type,self::clean_id($id)));foreach($users as $uid){self::emit('KnowledgeWatchTriggered.v1',array('user_id'=>(int)$uid,'object_type'=>$type,'object_id'=>$id,'source_event'=>$event,'delivery_owner'=>'file-19'));}}
    public static function notification_events($catalog){$catalog=is_array($catalog)?$catalog:array();$catalog['KnowledgeWatchTriggered.v1']=array('producer'=>'file-06','delivery_owner'=>'file-19','category'=>'knowledge','mandatory'=>false);$catalog['KnowledgeEvidenceReviewRequired.v1']=array('producer'=>'file-06','delivery_owner'=>'file-19','category'=>'knowledge-integrity','mandatory'=>true);return $catalog;}

    /* F06-FUT-017 Governed Multilingual Knowledge Editions. */
    public static function translation_list(WP_REST_Request $request){global $wpdb;$concept=self::concept($request->get_param('concept'));if(!$concept){return new WP_Error('he_not_found','Concept not found.',array('status'=>404));}$rows=$wpdb->get_results($wpdb->prepare("SELECT target_language,source_version,translation_version,status,machine_assisted,updated_at FROM ".self::table('translations')." WHERE concept_id=%d ORDER BY target_language,translation_version DESC",(int)$concept['id']),ARRAY_A);return rest_ensure_response(array('concept'=>$concept['public_id'],'translations'=>$rows));}
    public static function translation_save(WP_REST_Request $request){global $wpdb;$concept=self::concept($request->get_param('concept'));if(!$concept){return new WP_Error('he_not_found','Concept not found.',array('status'=>404));}$target=sanitize_text_field($request->get_param('target_language'));if(!in_array($target,array('ur-PK','ar','en-US'),true)){return new WP_Error('he_translation_language','Unsupported language.',array('status'=>400));}$content=$request->get_param('content');if(!is_array($content)||!$content){return new WP_Error('he_translation_content','Translation content is required.',array('status'=>400));}$table=self::table('translations');$next=1+(int)$wpdb->get_var($wpdb->prepare("SELECT MAX(translation_version) FROM {$table} WHERE concept_id=%d AND target_language=%s",(int)$concept['id'],$target));$status=HE_V2_Auth::can(HE_V2_Auth::CAP_REVIEW)?sanitize_key($request->get_param('status')?:'review'):'draft';if(!in_array($status,array('draft','review','approved','translation-outdated'),true)){$status='draft';}$wpdb->insert($table,array('concept_id'=>(int)$concept['id'],'source_language'=>$concept['language']??'en-US','target_language'=>$target,'source_version'=>(int)$concept['current_version'],'translation_version'=>$next,'content_json'=>self::json($content),'status'=>$status,'machine_assisted'=>empty($request['machine_assisted'])?0:1,'translator_id'=>get_current_user_id(),'reviewer_id'=>'approved'===$status?get_current_user_id():0,'content_hash'=>self::hash($content),'created_at'=>self::now(),'updated_at'=>self::now()));self::provenance('translation',(string)$wpdb->insert_id,'created',array('concept'=>$concept['public_id'],'target_language'=>$target,'source_version'=>(int)$concept['current_version'],'translation_version'=>$next,'status'=>$status));return rest_ensure_response(array('translation_id'=>(int)$wpdb->insert_id,'version'=>$next,'status'=>$status));}
    private static function mark_translations_outdated($public_id){global $wpdb;$concept=self::concept($public_id);if(!$concept){return;}$wpdb->query($wpdb->prepare("UPDATE ".self::table('translations')." SET status='translation-outdated',updated_at=%s WHERE concept_id=%d AND source_version<%d AND status='approved'",self::now(),(int)$concept['id'],(int)$concept['current_version']));}

    /* F06-FUT-018 Encyclopedia Integrity Command Center. */
    public static function command_center(){global $wpdb;$counts=array();$counts['review_required_external']=(int)$wpdb->get_var("SELECT COUNT(*) FROM ".self::table('external_links')." WHERE status='review-required'");$counts['open_evidence_gaps']=(int)$wpdb->get_var("SELECT COUNT(*) FROM ".self::table('evidence_gaps')." WHERE state='open'");$counts['pending_impacts']=(int)$wpdb->get_var("SELECT COUNT(*) FROM ".self::table('impact_queue')." WHERE state='pending'");$counts['outdated_translations']=(int)$wpdb->get_var("SELECT COUNT(*) FROM ".self::table('translations')." WHERE status='translation-outdated'");$counts['unreviewed_claims']=(int)$wpdb->get_var("SELECT COUNT(*) FROM ".self::table('claims')." WHERE status IN ('draft','review')");$counts['watched_objects']=(int)$wpdb->get_var("SELECT COUNT(DISTINCT CONCAT(object_type,':',object_id)) FROM ".self::table('watches'));$health=HE_V22_Operations::health();return rest_ensure_response(array('owner'=>'file-06','security_owner'=>'file-24','visual_owner'=>'file-25','notification_owner'=>'file-19','generated_at'=>gmdate('c'),'counts'=>$counts,'operational_health'=>$health,'autonomous_high_risk_actions'=>false));}

    public static function extend_contract($contracts){$contracts=is_array($contracts)?$contracts:array();if(isset($contracts['file-06'])&&is_array($contracts['file-06'])){$contracts['file-06']['future_intelligence_version']='1.0';$contracts['file-06']['future_requirements']=array('F06-FUT-001','F06-FUT-002','F06-FUT-003','F06-FUT-004','F06-FUT-005','F06-FUT-006','F06-FUT-007','F06-FUT-008','F06-FUT-009','F06-FUT-010','F06-FUT-011','F06-FUT-012','F06-FUT-013','F06-FUT-014','F06-FUT-015','F06-FUT-016','F06-FUT-017','F06-FUT-018');$contracts['file-06']['external_evidence_providers']=array('crossref','pubmed','clinicaltrials','orcid','datacite','mesh');$contracts['file-06']['future_routes']=self::NS;$contracts['file-06']['notification_delivery_owner']='file-19';}return $contracts;}
    public static function dashboard_projection($providers){$providers=is_array($providers)?$providers:array();if(isset($providers['file-06'])&&is_array($providers['file-06'])){$providers['file-06']['integrity_command_center']=array(__CLASS__,'command_center_snapshot');$providers['file-06']['future_intelligence']='F06-FUT-001..018';}return $providers;}
    public static function command_center_snapshot(){if(!HE_V2_Auth::can(HE_V2_Auth::CAP_REVIEW)){return new WP_Error('he_forbidden','Not authorized.');}$response=self::command_center();return $response instanceof WP_REST_Response?$response->get_data():$response;}
    private static function emit($event,$payload){$payload=is_array($payload)?$payload:array();$payload['producer']='file-06';$payload['contract_version']=HE_CONTRACT_VERSION;$payload['occurred_at']=gmdate('c');do_action('he_v2_event',$event,$payload,get_current_user_id(),self::uuid());}
}
