<?php
defined( 'ABSPATH' ) || exit;
final class HE_Privacy {
	public function hooks() { add_filter( 'wp_privacy_personal_data_exporters', array( $this, 'exporters' ) ); add_filter( 'wp_privacy_personal_data_erasers', array( $this, 'erasers' ) ); }
	public function exporters( $items ) { $items['homeopathy-encyclopedia'] = array( 'exporter_friendly_name' => 'Encyclopedia activity', 'callback' => array( $this, 'export' ) ); return $items; }
	public function erasers( $items ) { $items['homeopathy-encyclopedia'] = array( 'eraser_friendly_name' => 'Encyclopedia activity', 'callback' => array( $this, 'erase' ) ); return $items; }
	public function export( $email, $page = 1 ) { $user = get_user_by( 'email', $email ); if ( ! $user || $page > 1 ) { return array( 'data' => array(), 'done' => true ); } global $wpdb; $data = array(); foreach ( $wpdb->get_col( $wpdb->prepare( "SELECT entry_id FROM {$wpdb->prefix}he_bookmarks WHERE user_id=%d", $user->ID ) ) as $id ) { $data[] = array( 'name' => 'Bookmarked entry', 'value' => get_the_title( $id ) ); } foreach ( $wpdb->get_results( $wpdb->prepare( "SELECT * FROM {$wpdb->prefix}he_feedback WHERE user_id=%d", $user->ID ) ) as $row ) { $data[] = array( 'name' => ucfirst( $row->kind ), 'value' => get_the_title( $row->entry_id ) . ' — ' . $row->reason . ' — ' . $row->details . ' — ' . $row->status ); } return array( 'data' => $data ? array( array( 'group_id' => 'homeopathy-encyclopedia', 'group_label' => 'Encyclopedia', 'item_id' => 'user-' . $user->ID, 'data' => $data ) ) : array(), 'done' => true ); }
	public function erase( $email, $page = 1 ) { $user = get_user_by( 'email', $email ); if ( ! $user || $page > 1 ) { return array( 'items_removed' => false, 'items_retained' => false, 'messages' => array(), 'done' => true ); } global $wpdb; $removed = $wpdb->delete( $wpdb->prefix . 'he_bookmarks', array( 'user_id' => $user->ID ), array( '%d' ) ) > 0; $removed = $wpdb->delete( $wpdb->prefix . 'he_feedback', array( 'user_id' => $user->ID ), array( '%d' ) ) > 0 || $removed; $authored = count_user_posts( $user->ID, HE_Content::TYPE, true ); return array( 'items_removed' => $removed, 'items_retained' => $authored > 0, 'messages' => $authored ? array( 'Published entries and editorial audit history are retained for platform integrity.' ) : array(), 'done' => true ); }
}

