<?php
defined( 'ABSPATH' ) || exit;
final class HE_Interactions {
	public function hooks() { add_action( 'wp_ajax_he_interaction', array( $this, 'ajax' ) ); add_action( 'template_redirect', array( $this, 'view' ) ); }
	public function ajax() { check_ajax_referer( 'he_interaction', 'nonce' ); if ( ! is_user_logged_in() ) { wp_send_json_error( array( 'message' => 'Please log in to use this action.' ), 401 ); } $user = get_current_user_id(); $entry = isset( $_POST['entryId'] ) ? absint( $_POST['entryId'] ) : 0; $kind = isset( $_POST['kind'] ) ? sanitize_key( wp_unslash( $_POST['kind'] ) ) : ''; if ( HE_Content::TYPE !== get_post_type( $entry ) || 'publish' !== get_post_status( $entry ) ) { wp_send_json_error( array( 'message' => 'Entry not found.' ), 404 ); } $key = 'he_action_' . $user; $count = absint( get_transient( $key ) ); if ( $count >= 30 ) { wp_send_json_error( array( 'message' => 'Please wait before trying again.' ), 429 ); } set_transient( $key, $count + 1, MINUTE_IN_SECONDS ); if ( 'bookmark' === $kind ) { $active = $this->toggle( $user, $entry ); wp_send_json_success( array( 'active' => $active, 'label' => $active ? 'Bookmarked' : 'Bookmark' ) ); } if ( in_array( $kind, array( 'correction', 'report' ), true ) ) { $this->feedback( $user, $entry, $kind ); wp_send_json_success( array( 'message' => 'Thank you. The editorial team will review your submission.' ) ); } wp_send_json_error( array( 'message' => 'Unknown action.' ), 400 ); }
	private function toggle( $user, $entry ) { global $wpdb; $table = $wpdb->prefix . 'he_bookmarks'; $id = $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$table} WHERE user_id=%d AND entry_id=%d", $user, $entry ) ); if ( $id ) { $wpdb->delete( $table, array( 'id' => absint( $id ) ), array( '%d' ) ); return false; } $wpdb->insert( $table, array( 'user_id' => $user, 'entry_id' => $entry, 'created_at' => current_time( 'mysql', true ) ), array( '%d', '%d', '%s' ) ); return true; }
	private function feedback( $user, $entry, $kind ) { global $wpdb; $reasons = 'correction' === $kind ? array( 'typographical', 'broken-reference', 'incorrect-relationship', 'outdated-information', 'medical-safety', 'other' ) : array( 'medical-safety', 'spam', 'harassment', 'copyright', 'inappropriate', 'other' ); $reason = isset( $_POST['reason'] ) ? sanitize_key( wp_unslash( $_POST['reason'] ) ) : ''; $details = isset( $_POST['details'] ) ? sanitize_textarea_field( wp_unslash( $_POST['details'] ) ) : ''; if ( ! in_array( $reason, $reasons, true ) || ! trim( $details ) ) { wp_send_json_error( array( 'message' => 'Choose a valid reason and provide details.' ), 400 ); } $details = function_exists( 'mb_substr' ) ? mb_substr( $details, 0, 1500 ) : substr( $details, 0, 1500 ); $wpdb->insert( $wpdb->prefix . 'he_feedback', array( 'entry_id' => $entry, 'user_id' => $user, 'kind' => $kind, 'reason' => $reason, 'details' => $details, 'status' => 'open', 'created_at' => current_time( 'mysql', true ) ), array( '%d', '%d', '%s', '%s', '%s', '%s', '%s' ) ); }
	public function view() { if ( ! is_singular( HE_Content::TYPE ) ) { return; } $id = get_queried_object_id(); $cookie = 'he_viewed_' . $id; if ( isset( $_COOKIE[ $cookie ] ) ) { return; } update_post_meta( $id, '_he_views', absint( HE_Content::meta( $id, 'views' ) ) + 1 ); setcookie( $cookie, '1', array( 'expires' => time() + 12 * HOUR_IN_SECONDS, 'path' => COOKIEPATH ? COOKIEPATH : '/', 'secure' => is_ssl(), 'httponly' => true, 'samesite' => 'Lax' ) ); }
	public static function bookmarked( $entry, $user = 0 ) { global $wpdb; $user = $user ? absint( $user ) : get_current_user_id(); return $user && (bool) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->prefix}he_bookmarks WHERE user_id=%d AND entry_id=%d", $user, absint( $entry ) ) ); }
	public static function actions( $entry ) { $logged = is_user_logged_in(); $saved = $logged && self::bookmarked( $entry ); ob_start(); ?><div class="he-actions" data-he-actions><?php if ( $logged ) : ?><button type="button" data-he-action="bookmark" class="<?php echo $saved ? 'is-active' : ''; ?>" aria-pressed="<?php echo $saved ? 'true' : 'false'; ?>"><?php echo $saved ? 'Bookmarked' : 'Bookmark'; ?></button><details><summary>Suggest Correction</summary><?php echo self::feedback_form( 'correction' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></details><details><summary>Report</summary><?php echo self::feedback_form( 'report' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></details><?php else : ?><a href="<?php echo esc_url( wp_login_url( get_permalink( $entry ) ) ); ?>">Log in to bookmark or suggest a correction</a><?php endif; ?><span><?php echo absint( HE_Content::meta( $entry, 'views' ) ); ?> views</span></div><?php return ob_get_clean(); }
	private static function feedback_form( $kind ) { $items = 'correction' === $kind ? array( 'typographical' => 'Typographical correction', 'broken-reference' => 'Broken reference', 'incorrect-relationship' => 'Incorrect relationship', 'outdated-information' => 'Outdated information', 'medical-safety' => 'Medical safety concern', 'other' => 'Other' ) : array( 'medical-safety' => 'Medical safety concern', 'spam' => 'Spam', 'harassment' => 'Harassment', 'copyright' => 'Copyright concern', 'inappropriate' => 'Inappropriate content', 'other' => 'Other' ); $out = '<form data-he-feedback data-kind="' . esc_attr( $kind ) . '"><select name="reason" required><option value="">Choose reason</option>'; foreach ( $items as $key => $label ) { $out .= '<option value="' . esc_attr( $key ) . '">' . esc_html( $label ) . '</option>'; } return $out . '</select><textarea name="details" maxlength="1500" required placeholder="Describe the issue clearly"></textarea><button type="submit">Send</button></form>'; }
}

