<?php
defined( 'ABSPATH' ) || exit;
final class HE_Activator {
	public static function activate() { HE_Content::register(); HE_Content::seed_types(); self::role(); self::tables(); self::pages(); self::starters(); update_option( 'he_version', HE_VERSION, false ); set_transient( 'he_activation_notice', '1', 120 ); flush_rewrite_rules(); }
	public static function deactivate() { flush_rewrite_rules(); }
	private static function role() { $admin = get_role( 'administrator' ); if ( $admin ) { $admin->add_cap( 'manage_homeopathy_encyclopedia' ); } }
	private static function tables() { global $wpdb; require_once ABSPATH . 'wp-admin/includes/upgrade.php'; $c = $wpdb->get_charset_collate(); dbDelta( "CREATE TABLE {$wpdb->prefix}he_bookmarks (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,user_id bigint(20) unsigned NOT NULL,entry_id bigint(20) unsigned NOT NULL,created_at datetime NOT NULL,PRIMARY KEY  (id),UNIQUE KEY user_entry (user_id,entry_id),KEY user_id (user_id)) {$c};" ); dbDelta( "CREATE TABLE {$wpdb->prefix}he_feedback (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,entry_id bigint(20) unsigned NOT NULL,user_id bigint(20) unsigned NOT NULL,kind varchar(20) NOT NULL,reason varchar(40) NOT NULL,details text NOT NULL,status varchar(20) NOT NULL DEFAULT 'open',created_at datetime NOT NULL,PRIMARY KEY  (id),KEY entry_id (entry_id),KEY status (status)) {$c};" ); dbDelta( "CREATE TABLE {$wpdb->prefix}he_audit_log (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,entry_id bigint(20) unsigned NOT NULL,actor_id bigint(20) unsigned NOT NULL,action varchar(30) NOT NULL,note text NOT NULL,created_at datetime NOT NULL,PRIMARY KEY  (id),KEY entry_id (entry_id)) {$c};" ); }
	private static function pages() { $map = (array) get_option( 'he_page_map', array() ); $map['submit'] = self::page( 'Submit Encyclopedia Entry', 'submit-encyclopedia-entry', '[he_submit_entry]' ); $map['saved'] = self::page( 'Saved Knowledge', 'saved-knowledge', '[he_saved_entries]' ); update_option( 'he_page_map', $map, false ); }
	private static function page( $title, $slug, $shortcode ) { $p = get_page_by_path( $slug ); if ( $p instanceof WP_Post ) { return $p->ID; } $id = wp_insert_post( array( 'post_type' => 'page', 'post_status' => 'publish', 'post_title' => $title, 'post_name' => $slug, 'post_content' => $shortcode ), true ); if ( ! is_wp_error( $id ) ) { update_post_meta( $id, '_he_managed_page', '1' ); return $id; } return 0; }
	private static function starters() { $items = array(
		array( 'How to Use This Encyclopedia', 'clinical-terminology', 'A guide to searching, reviewing relationships, checking references, and distinguishing education from personal medical advice.', 'Use the search, A–Z index, knowledge types, and related-entry links to explore the encyclopedia. Entries are educational summaries. They must not be used as an automatic diagnosis or personal prescription.', '', 'Always seek qualified care for urgent, severe, persistent, or worsening symptoms.' ),
		array( 'Classical Homeopathy: An Educational Definition', 'homeopathy-philosophy', 'A neutral orientation to the historical concepts and study vocabulary of classical homeopathy.', 'Classical homeopathy is a historical system of complementary medicine associated with Samuel Hahnemann. Its literature emphasizes individualized symptom observation and the principle commonly described as “like cures like.” This entry describes the field; it does not establish effectiveness for a specific condition.', '', 'Do not delay evidence-based diagnosis, emergency treatment, vaccination, or other necessary medical care.' ),
		array( 'Introduction to Symptom Analysis', 'symptom', 'A structured introduction to location, sensation, modalities, timing, intensity, and accompanying features.', 'Symptom analysis organizes what a person experiences into clear descriptive elements. Careful description can improve communication with qualified clinicians and support educational case study.', '', 'Sudden neurological symptoms, severe breathing difficulty, chest pain, major bleeding, or loss of consciousness require urgent medical assessment.' ),
		array( 'The Educational Role of Anatomy and Pathology', 'anatomy', 'Why basic structure, function, and disease mechanisms matter in responsible health education.', 'Anatomy describes body structure. Pathology studies disease processes and their effects. Both are essential for recognizing the limits of complementary-health discussion and the need for appropriate investigation or referral.', 'Human Body', 'Educational summaries do not replace examination, laboratory testing, imaging, or specialist assessment.' ),
		array( 'Recognizing General Medical Red Flags', 'health-condition', 'A general safety entry describing warning signs that may need urgent or emergency care.', 'Red flags are warning signs that may indicate a serious condition. Examples include severe breathing difficulty, chest pressure, new one-sided weakness, uncontrolled bleeding, a seizure, sudden confusion, or rapidly worsening illness.', '', 'Contact local emergency services for life-threatening symptoms. Online educational content must not delay urgent assessment.' ),
	); foreach ( $items as $item ) { $found = get_posts( array( 'post_type' => HE_Content::TYPE, 'post_status' => 'any', 'title' => $item[0], 'posts_per_page' => 1, 'fields' => 'ids' ) ); if ( $found ) { continue; } $id = wp_insert_post( array( 'post_type' => HE_Content::TYPE, 'post_status' => 'publish', 'post_title' => $item[0], 'post_excerpt' => $item[2], 'post_content' => $item[3], 'post_author' => HE_Permissions::founder_id(), 'comment_status' => 'open' ), true ); if ( ! is_wp_error( $id ) ) { HE_Content::assign( $id, $item[1] ); update_post_meta( $id, '_he_body_system', $item[4] ); update_post_meta( $id, '_he_red_flags', $item[5] ); update_post_meta( $id, '_he_safety', 'Educational information only. Results and individual circumstances vary.' ); update_post_meta( $id, '_he_references', 'World Health Organization and local emergency-care guidance should be consulted for current public-health and urgent-care information.' ); update_post_meta( $id, '_he_language', 'en-US' ); update_post_meta( $id, '_he_views', 0 ); } } }
}

