#!/usr/bin/env python3
from pathlib import Path
p=Path('homeopathy-encyclopedia/includes/class-he-v242-language-surfaces.php')
s=p.read_text(encoding='utf-8')
old="""\tpublic static function normalize_language_meta( $meta_id, $object_id, $meta_key, $meta_value ) {\n\t\tif ( self::$normalizing || '_he_language' !== $meta_key || HE_V2_Domain::ENTRY_TYPE !== get_post_type( $object_id ) ) { return; }\n\t\t$canonical = HE_V242_Multilingual::canonical_locale( $meta_value );\n\t\tif ( ! $canonical || $canonical === (string) $meta_value ) { return; }\n\t\tself::$normalizing = true;\n\t\tupdate_post_meta( $object_id, '_he_language', $canonical );\n\t\tself::$normalizing = false;\n\t}\n"""
new="""\tpublic static function normalize_language_meta( $meta_id, $object_id, $meta_key, $meta_value ) {\n\t\tif ( self::$normalizing || '_he_language' !== $meta_key || HE_V2_Domain::ENTRY_TYPE !== get_post_type( $object_id ) ) { return; }\n\t\t$canonical = HE_V242_Multilingual::canonical_locale( $meta_value );\n\t\tif ( ! $canonical ) {\n\t\t\tHE_V2_Schema::record_runtime_failure( 'invalid_source_language', 'An invalid source-language code was rejected during metadata normalization.' );\n\t\t\treturn;\n\t\t}\n\t\tif ( $canonical !== (string) $meta_value ) {\n\t\t\tself::$normalizing = true;\n\t\t\tupdate_post_meta( $object_id, '_he_language', $canonical );\n\t\t\tself::$normalizing = false;\n\t\t}\n\t\tglobal $wpdb;\n\t\t$concept = $wpdb->get_row( $wpdb->prepare( 'SELECT id,language,public_id FROM ' . HE_V2_Schema::table( 'concepts' ) . ' WHERE post_id=%d', absint( $object_id ) ), ARRAY_A );\n\t\tif ( ! $concept || $canonical === (string) $concept['language'] ) { return; }\n\t\t$wpdb->update( HE_V2_Schema::table( 'concepts' ), array( 'language' => $canonical, 'updated_at' => current_time( 'mysql', true ) ), array( 'id' => (int) $concept['id'] ), array( '%s','%s' ), array( '%d' ) );\n\t\tif ( class_exists( 'HE_V24_Migration_Safety' ) && HE_V24_Migration_Safety::ready() ) {\n\t\t\t$wpdb->query( $wpdb->prepare( \"UPDATE \" . HE_V24_Future_Schema::table( 'translations' ) . \" SET status='translation-outdated',updated_at=UTC_TIMESTAMP() WHERE concept_id=%d AND source_locale<>%s AND status IN ('draft','approved','published')\", (int) $concept['id'], $canonical ) );\n\t\t\tHE_V24_Future_Schema::queue_impact( 'concept', $concept['public_id'], 'KnowledgeTranslationOutdated.v1', array( 'concept_id' => $concept['public_id'], 'reason' => 'source-language-changed' ) );\n\t\t}\n\t\tHE_V242_Third_Audit::repair_canonical_alias_language( $object_id, get_post( $object_id ), true );\n\t}\n"""
if old not in s:
    raise SystemExit('round6 target block not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
print('round6 source-language truth synchronization applied')
