#!/usr/bin/env python3
from pathlib import Path
p=Path('homeopathy-encyclopedia/includes/class-he-v2-integrations.php')
s=p.read_text(encoding='utf-8')
old1="""\tpublic static function composer_create_draft( $payload, $context = array() ) {\n\t\t$actor_id = isset( $context['actor_id'] ) ? absint( $context['actor_id'] ) : get_current_user_id();\n\t\tif ( ! $actor_id || ! HE_V2_Auth::can( HE_V2_Auth::CAP_EDIT ) ) {\n\t\t\treturn new WP_Error( 'he_composer_forbidden', __( 'File 06 creation is not authorized.', 'homeopathy-encyclopedia' ) );\n\t\t}\n\t\treturn HE_V2_Domain::create_entry( is_array( $payload ) ? $payload : array(), $actor_id );\n\t}\n"""
new1="""\tpublic static function composer_create_draft( $payload, $context = array() ) {\n\t\t$current_id = get_current_user_id();\n\t\t$actor_id = isset( $context['actor_id'] ) ? absint( $context['actor_id'] ) : $current_id;\n\t\tif ( ! $current_id || ! $actor_id || $actor_id !== $current_id ) {\n\t\t\treturn new WP_Error( 'he_composer_actor_mismatch', __( 'Composer actor attribution must match the authenticated user.', 'homeopathy-encyclopedia' ), array( 'status' => 403 ) );\n\t\t}\n\t\tif ( ! HE_V2_Auth::provider_ready() || ! HE_V2_Auth::membership_allowed( $actor_id ) || ! HE_V2_Auth::can( HE_V2_Auth::CAP_EDIT, 0, 'file06-composer-create-entry', $actor_id ) ) {\n\t\t\treturn new WP_Error( 'he_composer_forbidden', __( 'File 06 creation is not authorized.', 'homeopathy-encyclopedia' ), array( 'status' => 403 ) );\n\t\t}\n\t\treturn HE_V2_Domain::create_entry( is_array( $payload ) ? $payload : array(), $actor_id );\n\t}\n"""
old2="""\tpublic static function composer_create_research( $payload, $context = array() ) {\n\t\t$actor_id = isset( $context['actor_id'] ) ? absint( $context['actor_id'] ) : get_current_user_id();\n\t\tif ( ! $actor_id || ! HE_V2_Auth::can( HE_V2_Auth::CAP_RESEARCH ) ) {\n\t\t\treturn new WP_Error( 'he_composer_forbidden', __( 'File 06 research creation is not authorized.', 'homeopathy-encyclopedia' ) );\n\t\t}\n\t\treturn HE_V2_Domain::create_research( is_array( $payload ) ? $payload : array(), $actor_id );\n\t}\n"""
new2="""\tpublic static function composer_create_research( $payload, $context = array() ) {\n\t\t$current_id = get_current_user_id();\n\t\t$actor_id = isset( $context['actor_id'] ) ? absint( $context['actor_id'] ) : $current_id;\n\t\tif ( ! $current_id || ! $actor_id || $actor_id !== $current_id ) {\n\t\t\treturn new WP_Error( 'he_composer_actor_mismatch', __( 'Composer actor attribution must match the authenticated user.', 'homeopathy-encyclopedia' ), array( 'status' => 403 ) );\n\t\t}\n\t\tif ( ! HE_V2_Auth::provider_ready() || ! HE_V2_Auth::membership_allowed( $actor_id ) || ! HE_V2_Auth::can( HE_V2_Auth::CAP_RESEARCH, 0, 'file06-composer-create-research', $actor_id ) ) {\n\t\t\treturn new WP_Error( 'he_composer_forbidden', __( 'File 06 research creation is not authorized.', 'homeopathy-encyclopedia' ), array( 'status' => 403 ) );\n\t\t}\n\t\treturn HE_V2_Domain::create_research( is_array( $payload ) ? $payload : array(), $actor_id );\n\t}\n"""
for old,new,label in [(old1,new1,'entry composer'),(old2,new2,'research composer')]:
    if old not in s: raise SystemExit(label+' block not found')
    s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
print('round9 composer actor binding applied')
